### ISSUE TITLE
Data element ICON_NAME doesn't exist in raw netweaver system

### ISSUE THREAD

**Issue by christianguenter2** [tricktresor/guidrasil#1]
Hi Enno,
I cannot install because data element ICON_NAME doesn't exit in NW 752 SP01 dev edition.

![image](https://user-images.githubusercontent.com/17437789/46814951-24172180-cd7a-11e8-9f09-e46beba3c4b1.png)

![image](https://user-images.githubusercontent.com/17437789/46815002-4a3cc180-cd7a-11e8-8610-def87219d09d.png)

**Comment by christianguenter2** [comment]
Other missing data elements:
- GUID16

**Comment by tricktresor** [comment]
Thanks!
