### ISSUE TITLE
missing type ZGUIDRASIL_CONTROL_LIST_CC

### ISSUE THREAD

**Issue by sandraros** [tricktresor/guidrasil#12]
Hi Christian, I've just downloaded your amazing tool (I dreamt of it for many years), but I've got the same issue as you had in #11, by pressing the button "get complete report".

In the code, the method GET_EVENT_PATTERN_PLUS of class ZCL_GUIDRASIL_BUILDER attempts to call the method create_code_complete of class zcl_guidrasil_code_creation, but this latter has a syntax error.
I could compile it by creating the missing objects ZGUIDRASIL_CONTROL_LIST_CC and ZGUIDRASIL_CONTROL_LIST_CC_T.

**Comment by tricktresor** [comment]
Sorry, @sandraros - didn't notice the bug...

It seems as if there is a bug in abapGit. I can see the two missing types in my package but it will not be selected in abapGit transaction...

I could add the missing objects by "force stage" but they still do not appear in my SAP repository in abapGit... :/

cheers
Enno
