### ISSUE TITLE
Missing types

### ISSUE THREAD

**Issue by christianguenter2** [tricktresor/guidrasil#3]
Hi Enno, 
there still some types missing.

- boolean_flg
- /inw/enh_ctls
- /inw/enhema_set
- /inw/if_enhema_control_func
- /INW/S_ENHEMA_SETTING_DIABOX
- /INW/S_ENHEMA_SETTING_TEXT

![image](https://user-images.githubusercontent.com/17437789/46860182-26c45600-ce10-11e8-8cd2-ea380eb9e622.png)

**Comment by tricktresor** [comment]
now everything works.
by chance.
;D
